language: android
android:
  components:
    - build-tools-23.0.1
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - export TERM=dumb
  - gradle --version



before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  - adb devices

script:
  # Performs tests (which will do a ./gradlew build task first)
  # Skips the uninstallAll task as it's always a fresh emulator
  # Does a logcat dump if anything fails
  #- ./gradlew connectedAndroidTest -x uninstallAll -PtestSize=small --info  || (adb logcat -d && echo "TESTS FAILED" && exit  1)
  ./gradlew build
